# Generated by Django 5.1.2 on 2024-10-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFunctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
