# Generated by Django 5.1.2 on 2024-11-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreFunctions', '0003_comment_replycomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='replycomment',
            options={'verbose_name': 'Reply Comment', 'verbose_name_plural': 'Reply Comments'},
        ),
    ]
