# Generated by Django 5.1.2 on 2025-04-15 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFunctions', '0006_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='coreFunctions.comment'),
        ),
    ]
