# Generated by Django 5.1.2 on 2025-04-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFunctions', '0007_alter_replycomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
