# Generated by Django 5.1.2 on 2024-10-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petownerprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
