# Generated by Django 5.1.2 on 2024-10-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0002_petownerprofile_slug_vetprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
