# Generated by Django 5.1.2 on 2024-11-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0003_vetprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
