# Generated by Django 5.1.2 on 2024-11-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0004_user_profile_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petownerprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='vetprofile',
            name='full_name',
        ),
    ]
