# Generated by Django 5.1.2 on 2024-11-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0005_remove_petownerprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_verification',
            field=models.BooleanField(default=False),
        ),
    ]
