# Generated by Django 5.1.2 on 2024-11-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0006_user_status_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetprofile',
            name='status_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
