# Generated by Django 5.1.2 on 2025-03-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0007_vetprofile_status_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='petownerprofile',
            name='credit_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
