# Generated by Django 5.1.2 on 2025-04-12 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0008_petownerprofile_credit_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petownerprofile',
            name='pet_image',
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('pet_image', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('vaccination_status', models.CharField(blank=True, max_length=200, null=True)),
                ('allergies', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='authUser.petownerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='authUser.vetprofile')),
            ],
        ),
    ]
