# Generated by Django 5.1.2 on 2025-04-18 15:26

import authUser.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_pet'),
        ('authUser', '0010_vetprofile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='appointment.appointment'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(blank=True, default='default-pet.png', null=True, upload_to='pet_images/'),
        ),
        migrations.AlterField(
            model_name='petownerprofile',
            name='human_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=authUser.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='vetprofile',
            name='vet_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=authUser.models.user_directory_path),
        ),
    ]
