# Generated by Django 5.1.2 on 2025-04-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0011_review_appointment_alter_pet_pet_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petownerprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
