# Generated by Django 5.1.2 on 2025-03-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_vetschedule_date_vetschedule_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
