# Generated by Django 5.1.2 on 2025-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pidx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('refund_failed', 'Refund Failed'), ('failed', 'Failed')], default='unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid_pending_approval', 'Paid - Pending Approval'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
