# Generated by Django 5.1.2 on 2025-04-16 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_amount_paid_appointment_pidx_and_more'),
        ('authUser', '0010_vetprofile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='authUser.pet'),
        ),
    ]
